microsoft/react-native-xaml

codegen/Codegen/Program.cs, package/src/Props.ts, package/src/Types.tsx
=> Package src

example/package.json, package/package.json, package/windows/ReactNativeXaml/XamlMetadata.cpp, package/windows/ReactNativeXaml/XamlMetadata.h, package/windows/ReactNativeXaml/XamlViewManager.cpp, package/windows/ReactNativeXaml/XamlViewManager.h, yarn.lock
=> Use IViewManagerCreateWithProperties

example/App.tsx, package/Codegen/TSTypes.cs, package/Codegen/TSTypes.tt, package/Codegen/TypeCreator.cs, package/Codegen/TypeCreator.tt, package/Codegen/TypeEvents.cs, package/Codegen/TypeEvents.tt, package/Codegen/Util.cs, package/package.json, package/src/Props.ts, package/src/Types.tsx, package/windows/ReactNativeXaml/Codegen/TypeCreator.g.cpp, package/windows/ReactNativeXaml/Codegen/TypeEvents.g.h, package/windows/ReactNativeXaml/Crc32Str.h, package/windows/ReactNativeXaml/ReactNativeXaml.vcxproj, package/windows/ReactNativeXaml/ReactNativeXaml.vcxproj.filters, package/windows/ReactNativeXaml/XamlMetadata.cpp, package/windows/ReactNativeXaml/XamlMetadata.h
Fixes #5
- Eliminate creator map, just use RoActivateInstance directly
- Factor out the common parts of event attachment handlers
- Re-do some of the event attachment handlers to improve foldability
=> [Perf] Reduce binary size from ~1.5 MB to 875 kB 

package/Codegen/Program.cs, package/Codegen/TypeEvents.cs, package/Codegen/TypeEvents.tt, package/windows/ReactNativeXaml/Codegen/TypeEvents.g.h, package/windows/ReactNativeXaml/XamlMetadata.cpp, package/windows/ReactNativeXaml/XamlMetadata.h, package/windows/ReactNativeXaml/XamlViewManager.cpp
=> Lazy event attachment and detach

package/windows/ReactNativeXaml/ReactNativeXaml.vcxproj, package/windows/ReactNativeXaml/ReactNativeXaml.vcxproj.filters, package/windows/ReactNativeXaml/packages.config
=> Update cppwinrt to reduce dll size by 300 kB!

USAGE.md, example/App.tsx, package/Codegen/TypeCreator.cs, package/Codegen/TypeCreator.tt, package/Codegen/Util.cs, package/package.json, package/windows/ReactNativeXaml/Codegen/TypeCreator.g.cpp, package/windows/ReactNativeXaml/XamlMetadata.cpp, package/windows/ReactNativeXaml/XamlMetadata.h, package/windows/ReactNativeXaml/XamlViewManager.cpp
=> NavigationView and add support for activating types with a custom activation factory

package/windows/ReactNativeXaml/XamlViewManager.cpp
=> Enable adding content to derived ContentControls

.github/workflows/main.yml, USAGE.md, package/windows/ReactNativeXaml/XamlViewManager.cpp
=> add support for AutoSuggestBox's QueryIcon property

package/package.json, package/windows/ReactNativeXaml/ReactNativeXaml.vcxproj
=> Support ExperimentalFeatures.props

package/package.json, package/windows/ReactNativeXaml/XamlMetadata.h
bottom and right were swapped when using json
=> Fix bug about Thickness values

package/package.json, package/windows/ReactNativeXaml/XamlMetadata.h
=> Allow int/double for Thickness property

package/Codegen/TSProps.cs, package/Codegen/TSProps.tt, package/package.json, package/src/Props.ts, package/windows/ReactNativeXaml/XamlMetadata.cpp
=> Fix GridLength to support number*, *, auto, and number

README.md
Updating the Codegen link in Readme: https://github.com/asklar/react-native-xaml/tree/main/package/Codegen
=> Updating broken Codegen link in the readme file

USAGE.md, package/Codegen/Model.cs, package/Codegen/Program.cs, package/Codegen/TSEnums.cs, package/Codegen/TSEnums.tt, package/Codegen/TSProps.cs, package/Codegen/TSProps.tt, package/Codegen/TypeEvents.cs, package/Codegen/TypeEvents.tt, package/Codegen/TypeProperties.cs, package/Codegen/TypeProperties.tt, package/Codegen/Util.cs, package/Codegen/Windows.UI.Xaml.json, package/package.json, package/src/Enums.ts, package/src/Props.ts, package/windows/ReactNativeXaml/Codegen/TypeEvents.g.h, package/windows/ReactNativeXaml/Codegen/TypeProperties.g.h, package/windows/ReactNativeXaml/ReactNativeXaml.vcxproj, package/windows/ReactNativeXaml/ReactNativeXaml.vcxproj.filters, package/windows/ReactNativeXaml/Serialize.cpp, package/windows/ReactNativeXaml/XamlMetadata.cpp, package/windows/ReactNativeXaml/XamlMetadata.h, package/windows/ReactNativeXaml/XamlObject.cpp, package/windows/ReactNativeXaml/XamlViewManager.cpp
=> ContentDialog API for opening and getting results

package/Codegen/Program.cs, package/package.json, package/windows/ReactNativeXaml/XamlViewManager.cpp
=> Add support for Viewbox

package/Codegen/Model.cs, package/Codegen/Windows.UI.Xaml.json, package/src/Props.ts, package/windows/ReactNativeXaml/Codegen/TypeProperties.g.h, package/windows/ReactNativeXaml/XamlMetadata.h
Support Style property to interface with XAML styles defined in the app or in winui/xaml
=> Style property

package/package.json, package/windows/ReactNativeXaml/ReactNativeXaml.vcxproj, package/windows/ReactNativeXaml/XamlViewManager.cpp, package/windows/ReactNativeXaml/packages.config
This PR adds CDebug messages on unhandled XamlViewManager methods.
=> Report unhandled ViewManager methods

USAGE.md, example/App.tsx, package/Codegen/Util.cs, package/Codegen/Windows.UI.Xaml.json, package/package.json, package/src/Enums.ts, package/windows/ReactNativeXaml/XamlViewManager.cpp, package/windows/ReactNativeXaml/pch.h, yarn.lock
=> Add support for Splitview

package/package.json, package/windows/ReactNativeXaml/XamlObject.cpp
=> serialize Color

example/App.tsx, package/package.json, package/windows/ReactNativeXaml/XamlViewManager.cpp
=> Support Icon in WinUI NavigationViewItem

package/package.json
=> Include config json in npm package

package/package.json, package/rebuild_projection.cmd, package/windows/ReactNativeXaml/ReactNativeXaml.vcxproj, package/windows/ReactNativeXaml/XamlObject.cpp
=> Improve custom component consumption

change/react-native-xaml-4bbc74e8-e01b-4bd6-b378-83bb9f02b4ee.json, change/react-native-xaml-5497d4a6-ba1a-4f3c-974a-2de4c6ae5fcc.json, package.json, package/CHANGELOG.json, package/CHANGELOG.md, package/package.json, package/windows/ReactNativeXaml/XamlViewManager.cpp
Adds support for MenuFlyoutItem icons
Closes #145
=> Menu flyout item icon

.github/workflows/SetUpAppForNuget.ps1, .github/workflows/main.yml
=> Add building CLI app in CI

change/react-native-xaml-53a10e31-7d4d-46f4-a4dd-6e477fab9c83.json, package/CHANGELOG.json, package/CHANGELOG.md, package/package.json, package/windows/ReactNativeXaml/Codegen/Version.g.h, package/windows/ReactNativeXaml/XamlViewManager.cpp
=> Support InfoBar button

USAGE.md, package/Codegen/Windows.UI.Xaml.json, package/src/Enums.ts, package/windows/ReactNativeXaml/Codegen/TypeEnums.g.h, package/windows/ReactNativeXaml/XamlViewManager.cpp
=> NavigationView Content property

change/react-native-xaml-6f724d4b-ade8-41a4-9c88-38a1a9898879.json, package/CHANGELOG.json, package/CHANGELOG.md, package/package.json, package/windows/ReactNativeXaml/Codegen/Version.g.h, package/windows/ReactNativeXaml/Styling.cpp
needed for microsoft/react-native-windows#9831
=> Remove implicit dependency on ColorHelper

.clang-format, CONTRIBUTING.md, USAGE.md, change/react-native-xaml-22e8f50a-9bc8-45db-a28e-f438d15eea98.json, package.json, package/CHANGELOG.json, package/CHANGELOG.md, package/package.json, package/windows/ReactNativeXaml/Codegen/Version.g.h, package/windows/ReactNativeXaml/XamlViewManager.cpp
=> Add support for MenuFlyoutSubItem

change/react-native-xaml-cc7e31ad-8d4d-4e90-8285-ab5d477c1459.json, package/CHANGELOG.json, package/CHANGELOG.md, package/Codegen/TypeCreator.cs, package/Codegen/TypeCreator.tt, package/package.json, package/windows/ReactNativeXaml/Codegen/TypeCreator.g.cpp, package/windows/ReactNativeXaml/Codegen/Version.g.h
Addresses a CodeQL issue tracked interally: https://microsoft.visualstudio.com/OS/_workitems/edit/40998055/
=> Codeql fix

change/react-native-xaml-6a4ff73d-3375-4842-aded-97da28555622.json, package/windows/ReactNativeXaml/XamlMetadata.h
Fixes #250 
This may be a compiler issue (since it only started to show up in recent msvc updates), but regardless it makes sense to simplify this code a bit anyway.
=> Simplify set prop value

change/react-native-xaml-baecfde6-658e-4686-8da0-8bb49112cb50.json, package/windows/ReactNativeXaml/ReactNativeXaml.vcxproj
This PR fixes several instances of improper quoting within the Conditions of ReactNativeXaml.vcxproj.
=> Fix unquoted properties in vcxproj conditions
