microsoft/react-native-xaml

example/App.tsx
package/windows/ReactNativeXaml/ReactNativeXaml.vcxproj
package/windows/ReactNativeXaml/ReactNativeXaml.vcxproj.filters
package/windows/ReactNativeXaml/Styling.cpp
package/windows/ReactNativeXaml/Styling.h
package/windows/ReactNativeXaml/XamlViewManager.cpp

This enables using lightweight styling from react-native-xaml via a new object-typed property "resources".
Updates to this property won't work since in UWP XAML, ResourceDictionary is a static resource and does not reevaluate an element's children when a member of the dictionary gets updated. Tracked by https://github.com/microsoft/microsoft-ui-xaml/issues/4443
Fixes #21

Lightweight styling

---

USAGE.md
package/Codegen/Util.cs
package/package.json
package/src/Props.ts
package/windows/ReactNativeXaml/Codegen/TypeProperties.g.h
package/windows/ReactNativeXaml/XamlMetadata.h

Fixes #100 
Special shoutout to @reflectronic for their tip to use XamlBindingHelper to do the heavy lifting of parsing a string into a Geometry!

Support Path.Data and other Geometry properties

---

package/windows/ReactNativeXaml/ReactNativeXaml.vcxproj
package/windows/ReactNativeXaml/ReactNativeXaml.vcxproj.filters
package/windows/ReactNativeXaml/Wrapper.cpp
package/windows/ReactNativeXaml/Wrapper.h
package/windows/ReactNativeXaml/Wrapper.idl
package/windows/ReactNativeXaml/XamlMetadata.cpp
package/windows/ReactNativeXaml/XamlMetadata.h
package/windows/ReactNativeXaml/XamlViewManager.cpp

Some clean up, makes the delineation between ContentControl and the non-FrameworkElement wrapping container explicit.

Use separate type for the non-FE wrapper

---

package/Codegen/Program.cs
package/Codegen/Util.cs
package/package.json

When following the steps on the [TechnicalGuide](https://github.com/microsoft/react-native-xaml/blob/main/TechnicalGuide.md), `codegen.exe` would produce the following error because it would look for the config file in the current working directory (instead of where the file was located by default):
```ps
Unhandled exception. System.IO.FileNotFoundException: Could not find file 'X:\...\myProject\Windows.UI.Xaml.json'.
File name: 'X:\...\myProject\Windows.UI.Xaml.json'
at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
...
````
**Fixed by changing the default lookup path to be in the same directory as `Codegen.exe`**
----------
Additionally, there was a bug where [custom] …

Codegen.exe bug fixes for config file default location and namespace parsing

---

.github/workflows/publish.yml

This PR attempts to separate the publish process into two steps, the
first part verifying the codegen is up to date (on Windows), the second
part doing the actual yarn build and publish on ubuntu.

Update publish workflow to build on Windows, publish on Ubuntu

---

example/windows/example/App.cpp

**_Why_**
Remove UseJsi() Call from example app. This API was deprecated in 0.65; it causes the app build to fail. 
Fixes #180

Remove UseJsi() Call from Example

---

change/react-native-xaml-61f76b05-db43-4e57-9d58-5973b3eafa76.json
package/CHANGELOG.json
package/CHANGELOG.md
package/Codegen/TSTypes.cs
package/Codegen/TSTypes.tt
package/package.json
package/src/Types.tsx
package/windows/ReactNativeXaml/Codegen/Version.g.h

Fixes error when running jest in an RNW app. Tests fail with error that UIManager.getViewManagerConfig('XamlControl') returns undefined. This is most likely because of an order of operations issue with Jest's mocking functionality. Moving this code snippet to where the code is being used resolves the issue.

Fix Error When Running Jest

---

change/react-native-xaml-6fc7297b-4bc6-41a0-89dd-464fd20a7485.json
package/CHANGELOG.json
package/CHANGELOG.md
package/package.json
package/windows/ReactNativeXaml/Codegen/Version.g.h
package/windows/ReactNativeXaml/XamlMetadata.cpp

It's `XamlHelper::GetReactTag` and `XamlHelper::SetReactTag`, not
`XamlHelper::GetTag` and `XamlHelper::SetTag`.

Fix build break when RNW_REACTTAG_API is defined

---

.github/workflows/SetUpAppForNuget.ps1
.github/workflows/main.yml
change/react-native-xaml-8fc0e6e6-482a-4c20-85c0-d1e46247b16b.json
package/windows/ReactNativeXaml/ReactNativeXaml.vcxproj

This PR checks if the version of RNW is >= 0.68.0, then switches to using
`PackageReference` for NuGet dependencies instead of using the legacy
`packages.config`.
This PR also updates the GitHub Action workflow to reduce copy/pasting and expand the test matrix of RNW versions tested.
Closes #230
Closes #231

Enable PackageReference support if available

---

change/react-native-xaml-a8381afc-a56c-4494-957c-ee7962956d9a.json
package/windows/ExperimentalFeatures.props
package/windows/ReactNativeXaml/ReactNativeXaml.vcxproj

This PR adds some new MSBuild properties and targets within ReactNativeXaml.vcxproj to support re-running the CodeGen before the build.
By setting a property in their ExperimentalFeatures.props file:
```xml
<RunReactNativeXamlCodeGenBeforeBuild>true</RunReactNativeXamlCodeGenBeforeBuild>
```
Customers can make sure the CodeGen tool runs before the native build. It's default to `false` since most customers don't need it. However, this will hopefully address https://github.com/microsoft/react-native-windows/issues/10792, which was a hack to get the same effect.
Note that customers can also customize how the CodeGen runs, in particular, by specifying a different `ReactNativeXamlTargetWinMD` file if desired.

Add target to optionally run CodeGen before ReactNativeXaml build

---

LICENSE
change/react-native-xaml-a5d640ee-506a-4d00-aaa1-3a2b931ea4c4.json
package/LICENSE
package/README.md

This PR is to capture that the codegen was retargeted to WinUI 2.7 (to align with the supported versions of RNW).

Upgrade to WinUI 2.7

---

change/react-native-xaml-2081187e-e006-4295-a34d-3985fb4ebe93.json
package/Codegen/TypeEvents.cs
package/Codegen/TypeEvents.tt
package/windows/ReactNativeXaml/Codegen/TypeEvents.g.h
package/windows/ReactNativeXaml/XamlMetadata.cpp
package/windows/ReactNativeXaml/XamlMetadata.h

The current implementation of `JsiDispatchEvent` calls directly into `callFunctionReturnFlushedQueue` to trigger a call into the JS code.  Unfortunately, this call returns an array which is a list of native module calls which should be made.  But this code is not able to call those native modules since that code is not exposed.  So instead, there are just a set of native module calls which never get called.
This PR replaces the call to `callFunctionReturnFlushedQueue` with a call directly into the `RCTEventEmitter.receiveEvent` function, which will not do the flush.
The flush will be done by the `ExecuteJsi` function, which will correctly flush and call the native modules returned.
Fixes https://github.com/microsoft/react-native-xaml/issues/247

Avoid throwing away native module calls

---

.github/workflows/pr.yml

Our PR jobs now call into templates and use a matrix strategy for all tested configurations.
GitHub Actions branch protections do not let you set "all jobs are required" nor even "all matrix permutations of this one job" are required.
You literally have to set every individual permutation as required manually, which makes it hard to maintain.
This PR adds a final "Successful PR Check" job that is dependent on all the others, that can be the *one* set to required.

Add required PR Check action

---

.github/workflows/main.yml
.github/workflows/pr.yml
.github/workflows/template-testcli.yml

Now that typescript types are included in RN, they've deprecated the package `@types/react-native`, which unfortunately breaks creating new test apps for RN < 0.71 because RNX needs the types to do its codegen and they're no longer available.
This PR fixes our CI/PR workflows to use the typescript templates for the older versions so we get typescript and the proper RN types.

Fix missing TS dependency for RN < 0.71

---

.github/workflows/main.yml
.github/workflows/pr.yml
change/react-native-xaml-4147834d-ad37-47d7-83bc-245271fe2778.json
package/package.json

This PR bumps the minimum required/supported version of react-native and react-native-windows to 0.69.0.

Require RNW >= 0.69.0

---

change/react-native-xaml-e7cf68a9-d303-4f2d-8131-7866d5e54c6f.json
package/package.json
yarn.lock

react-native provides its own types now.

@types/react-native has been deprecated, so we should no longer bring it in

---

README.md
TechnicalGuide.md

This commit fixes links from `/asklar/react-native-xaml` to the current repo URL - `/microsoft/react-native-xaml`

Update & fix links in TechnicalGuide.md

---

.github/ISSUE_TEMPLATE/bug-report.yaml
.github/policies/resourceManagement.yml
.github/workflows/main.yml
.github/workflows/pr.yml
.github/workflows/template-buildexample.yml
.github/workflows/template-testcli.yml
change/react-native-xaml-1f9338d9-abf8-45df-b6b0-8f5af208803e.json
example/package.json
example/windows/ExperimentalFeatures.props
example/windows/example/packages.lock.json
examplenuget/package.json
examplenuget/windows/ExperimentalFeatures.props
examplenuget/windows/examplenuget/packages.lock.json
package/package.json
package/windows/ReactNativeXaml/packages.lock.json
yarn.lock

This PR is meant to fix the CI for `react-native-xaml` with the minimum number of changes required to pass, so that new development can continue.
A side-effect of this change is to bump the version of `react-native-windows` needed by the example apps from 0.73.4 to 0.73.21.

Fix CI pipelines and bump to RNW 0.73.21

---

change/react-native-xaml-dba300ac-4cad-41b2-a538-aeeac2e8b0a3.json
package/windows/ReactNativeXaml/XamlViewManager.cpp

Currently when number of MenuFlyoutItem change, they don't reflect in the MenuFlyout as expected. For example, if you have a MenuFlyout that looks like this:
Then something changes that removes Feedback on recommendation to be removed, the MenuFlyout appears like this:
instead of like this:
This PR fixes this issue.

Menuflyout fix

---

change/react-native-xaml-3440a323-4329-4f3e-af38-2181f6252927.json
package/.npmignore
package/package.json
package/windows/ReactNativeXaml/ReactNativeXaml.vcxproj

This PR fixes our consumption of the `Microsoft.Windows.CppWinRT` package reference to use `Update` instead of `Include` (so at best it "updates" which version to use and doesn't conflict with what RNW wants) and removes the "duplicate reference" warning our customers see.
I'm 99% we don't need the entry at all in newer RNW versions but leaving it for now to deal with older customers.
This PR also removes the NuGet `package.lock.json` file from the published npm package, as it takes the decision to use/respect lock files away from the customer.

Fix NuGet errors when consumed by apps
